### PR TITLE
Rename LICENCE → COPYING

### PR DESCRIPTION
**Pull request by filbertkm**
This is needed for the license link in Special:Version to work correctly.

### CODE REVIEW

**Comment by thiemowmde** [comment]
I wonder about the file name. About 15 of these files we have are called COPYING, only 5 are called LICENSE. Does this matter?

https://github.com/wikimedia/mediawiki/blob/master/includes/specials/SpecialVersion.php#L1094

There LICENSE file in this repository, but the special page scans for LICENSE. Ouch. I suggest we rename them all to COPYING.

**Comment by addshore** [comment]
I am confused by this PR and the first commit, as it seems there is already a LICENCE file on current master!

**Comment by thiemowmde** [comment]
Licen**c**e vs. licen**s**e.

**Comment by thiemowmde** [comment]
I squashed the two commits. The first commit added a LICENSE file, which was a duplicate of the existing LICENCE.

**Comment by addshore** [comment]
So now the PR is actually just moving the file to COPYING right?

**Comment by filbertkm** [comment]
@addshore MediaWiki uses American English to spell LICENSE.  it could probably easily be modified to also accept British English spellings :)

**Comment by filbertkm** [comment]
@thiemowmde i am confused by the squash.  I was renaming LICENCE to LICENSE and not duplicating the file.   I am ok with COPYING if that's what we prefer.

**Comment by addshore** [comment]
yeh, I decided to merge this and get it out of the way.
If we generally call more things COPYING then lets call them all COPYING.
Also if we use COPYING we have less likely hood of me miss spelling it etc ;)

**Comment by filbertkm** [comment]
COPYING is same in british and american english, so probably less confusing :)

**Comment by thiemowmde** [comment]
@filbertkm It was very obvious that there was a mistake in your first commit (for whatever reason), so I fixed it to get this going and save us all some time. I picked COPYING because it's not only more common in our libraries, it's also more common in other MediaWiki libraries.

**Pull request merged**
